train_test_split:
  test_size: 0.2
  random_state: 42

model:
  name: random_forest

random_forest:
  n_estimators: 200
  max_depth: 15
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42

evaluation:
  metrics:
    - rmse
    - mae
    - r2
